"""Prometheus metrics configuration for the application.

This module sets up and configures Prometheus metrics for monitoring the application.
"""

from typing import Tuple

from prometheus_client import Counter, Histogram, Gauge
from starlette.requests import Request
from starlette.routing import Match
from starlette_prometheus import metrics, PrometheusMiddleware

# starlette-prometheus assumes every route in `app.routes` is a leaf route with
# a `.path` attribute. Newer Starlette versions wrap `include_router()` output
# in a lazy `_IncludedRouter` container that has no `.path`, so the upstream
# implementation crashes on every request. Patch it to walk into sub-routers.


def _get_path_template(request: Request) -> Tuple[str, bool]:
    def _match(routes) -> Tuple[str, bool] | None:
        for route in routes:
            original_router = getattr(route, "original_router", None)
            if original_router is not None:
                found = _match(original_router.routes)
                if found:
                    return found
                continue
            match, _ = route.matches(request.scope)
            if match == Match.FULL:
                return route.path, True
        return None

    return _match(request.app.routes) or (request.url.path, False)


PrometheusMiddleware.get_path_template = staticmethod(_get_path_template)

# Request metrics
http_requests_total = Counter("http_requests_total", "Total number of HTTP requests", ["method", "endpoint", "status"])

http_request_duration_seconds = Histogram(
    "http_request_duration_seconds", "HTTP request duration in seconds", ["method", "endpoint"]
)

# Database metrics
db_connections = Gauge("db_connections", "Number of active database connections")

# Custom business metrics
orders_processed = Counter("orders_processed_total", "Total number of orders processed")

llm_inference_duration_seconds = Histogram(
    "llm_inference_duration_seconds",
    "Time spent processing LLM inference",
    ["model"],
    buckets=[0.1, 0.3, 0.5, 1.0, 2.0, 5.0],
)


llm_stream_duration_seconds = Histogram(
    "llm_stream_duration_seconds",
    "Time spent processing LLM stream inference",
    ["model"],
    buckets=[0.1, 0.5, 1.0, 2.0, 5.0, 10.0],
)

session_names_generated_total = Counter(
    "session_names_generated_total",
    "Total session names generated by the LLM",
    ["status"],  # "success" | "error"
)


def setup_metrics(app):
    """Set up Prometheus metrics middleware and endpoints.

    Args:
        app: FastAPI application instance
    """
    # Add Prometheus middleware
    app.add_middleware(PrometheusMiddleware)

    # Add metrics endpoint
    app.add_route("/metrics", metrics)
